### ISSUE TITLE
Cannot install extension: Unexpected EOF

### ISSUE THREAD

**Issue by retostadelmann** [lszomoru/vscode-vsts-workitems#1]
Any idea why? I'm using VSCode 0.10.3.

**Comment by lszomoru** [comment]
sorry about that. I have tried to reproduce the problem on my box but I was not able to do so. are there any details in the output window? Also I was wondering if you are able to reproduce the issue on more than one box? I will try to set up a clean box to see if I can repro it there and will circle back to you.

**Comment by retostadelmann** [comment]
No details in the output window, but as you mentioned it, i tried it on a virtual machine, where the installation worked. I'm trying to figure out the differences and come back to you with the solution.

**Comment by retostadelmann** [comment]
I now started VSCode as an Administrator (What i have not explicitly done on my virtual machine) and i could install your extension on my local machine. You can close this issue. Thank you for your help!

**Comment by lszomoru** [comment]
Glad to hear that you were able to successfully install the extension. Do let me know if you run into any other issues with the extension or if you have any feature request.
