### ISSUE TITLE
No handler found for the command: 'extension.openVSTSPortal'

### ISSUE THREAD

**Issue by ChaosieKinder** [lszomoru/vscode-vsts-workitems#2]
Getting an error clicking on the status bar label:

No handler found for the command: 'extension.openVSTSPortal'. Ensure there is an activation event defined, if you are an extension.

**Comment by lszomoru** [comment]
Sorry about that. I will take a look at that later today and will try to push an update to the extension.

**Comment by lszomoru** [comment]
This issue has been fixed in v0.0.3. Please update the extension. Thanks!
